spring.application.name=project


spring.datasource.url=jdbc:postgresql://localhost:5432/Inventory
spring.datasource.username=postgres
spring.datasource.password=12112005@shubhmishra
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-null-for-primitives=false
